global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
  - "rules-process-explorer.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.0.131:9090"]    
    basic_auth:
      username: "skynet"
      password: "prometheus"
   # password_file: ./web-config.yml

    # Node exporter
  - job_name: node
    static_configs:
      #- targets: ['localhost:9100']
      - targets: ["192.168.0.131:9100"]
    basic_auth:
      username: "skynet"
      password: "prometheus"
      #  password_file: ./web-config.yml

# remote write - to prometheus_1
remote_write:
  - url: "http://192.168.0.130:9090/api/v1/write"    
    queue_config:
      capacity: 10000
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms
    basic_auth:
      username: "skynet"
      password: "prometheus"
      #  password_file: ./web-config.yml
