global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.0.132:9090"]    
    basic_auth:
      username: "skynet"
      password: "prometheus"

  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'
    basic_auth:
      username: "skynet"
      password: "prometheus"

    params:
      # 'match[]':
      #   - '{job="prometheus"}'
      #   - '{__name__=~"job:.*"}'
      'match[]':
        - '{job!~"prometheus"}'

    static_configs:
      - targets:
        - '192.168.0.130:9090'
        - '192.168.0.131:9090'
